# nothing

name: Update regularly every hour

# daily job
on:
    push:
    schedule:
        -
            # every hour
            cron: 5 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -
                uses: actions/checkout@v2

            # Setup git
            -
                name: Setup Git Infomation
                run: |
                    git config --global user.name 'lelehub'
                    git config --global user.email '1449596563@qq.com'
            # Record (use record.sh or record2.sh)
            -
                name: Recording
                run: |
                    sh ./record.sh
            -
                name: Pushing
                run: |
                    git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
